for /f "usebackq tokens=6 delims=\" %%a in (`reg query hklm\system\controlset001\control\class /s /f "Network adapters"`) do set guid2=%%a
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*flowcontrol" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*interruptmoderation" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*ipchecksumoffloadipv4" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*jumbopacket" /t reg_sz /d "1514" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*lsov2ipv4" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*lsov2ipv6" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*pmarpoffload" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*pmnsoffload" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*priorityvlantag" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*receivebuffers" /t reg_sz /d "2048" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*rss" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*speedduplex" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*tcpchecksumoffloadipv4" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*tcpchecksumoffloadipv6" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*transmitbuffers" /t reg_sz /d "2048" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*udpchecksumoffloadipv4" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*udpchecksumoffloadipv6" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*wakeonmagicpacket" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*wakeonpattern" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "eeelinkadvertisement" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "enablemsi" /t reg_sz /d "00000001" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "enablepme" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "itr" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "loglinkstateevent" /t reg_sz /d "16" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "numrssqueues" /t reg_sz /d "4" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "receivescalingmode" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "reducespeedonpowerdown" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "sipsenabled" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "txintdelay" /t reg_sz /d "28" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "ulpmode" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "masterslave" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "wakeonlink" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "wakeonslot" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000\ndi\params\numrssqueues\enum" /v "3" /t reg_sz /d "3 queues" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000\ndi\params\numrssqueues\enum" /v "4" /t reg_sz /d "4 queues" /f
reg add "hklm\system\currentcontrolset\services\ndis\parameters" /v "maxnumrsscpus" /t reg_dword /d "4" /f
reg add "hklm\system\currentcontrolset\services\ndis\parameters" /v "rssbasecpu" /t reg_dword /d "0" /f
::new
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*txabsintdelay" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*rxabsintdelay" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*rxintdelay" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*llipush" /t reg_sz /d "1472" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*llisize" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*intmode" /t reg_sz /d "2" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*enablemsi" /t reg_dword /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*eee" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*speedduplex" /t reg_sz /d "6" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*rssprofile" /t reg_sz /d "4" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*numrssqueues" /t reg_sz /d "2" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "*alternatesemaphoredelay" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "masterslave" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "waitautonegcomplete" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "txintdelay" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "eee" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "loglinkstateevent" /t reg_sz /d "14" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "node" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "llipush" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "llisize" /t reg_sz /d "1472" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "intmode" /t reg_dword /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "txabsintdelay" /t reg_sz /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "rxabsintdelay" /t reg_dword /d "1" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "alternatesemaphoredelay" /t reg_sz /d "0" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "enable9kjftpt" /t reg_sz /d "0" /f
reg add "hklm\system\currentcontrolset\services\ndis\parameters" /v "maxnumrsscpus" /t reg_dword /d "2" /f
reg add "hklm\system\controlset001\control\class\%guid2%\0000" /v "numrssqueues" /t reg_sz /d "2" /f